services:
    semaphore_db:
        image: mysql:8
        environment:
            - MYSQL_USER=${SEMAPHORE_DB_USER}
            - MYSQL_PASSWORD=${SEMAPHORE_DB_PASS}
            - MYSQL_DATABASE=${SEMAPHORE_DB}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - semaphore_network
        restart: unless-stopped
    semaphore:
        ports:
            - 3444:3000
        depends_on:
            - semaphore_db
        image: semaphoreui/semaphore:v2.16.18
        user: "${UID}:${GID}"
        restart: unless-stopped
        environment:
            - SEMAPHORE_DB_DIALECT=mysql
            - SEMAPHORE_DB_HOST=semaphore_db
            - SEMAPHORE_DB_NAME=${SEMAPHORE_DB}
            - SEMAPHORE_DB_USER=${SEMAPHORE_DB_USER}
            - SEMAPHORE_DB_PASS=${SEMAPHORE_DB_PASS}
            - SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN}
            - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
            - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME}
            - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
            - SEMAPHORE_USE_REMOTE_RUNNER=True
            - SEMAPHORE_RUNNER_REGISTRATION_TOKEN=${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
            - SEMAPHORE_TOTP_ENABLED=True
            - SEMAPHORE_TOTP_ALLOW_RECOVERY=True
            - SEMAPHORE_SCHEDULE_TIMEZONE=Europe/Paris
            - SEMAPHORE_COOKIE_ENCRYPTION=${SEMAPHORE_COOKIE_ENCRYPTION}
            - SEMAPHORE_COOKIE_HASH=${SEMAPHORE_COOKIE_HASH}
        volumes:
            - ./inventory/:/inventory:ro # pour stocker les fichiers d'inventaire Ansible en lecture seule
            - ./semaphore_data:/var/lib/semaphore
            - ./semaphore_config:/etc/semaphore
        networks:
            - semaphore_network
volumes:
    mysql_data:

networks:
    semaphore_network:
        driver: bridge